### ISSUE TITLE
Power button

### ISSUE THREAD

**Issue by sbur83** [LaskaKit/ESPD-35#6]
I have uploaded to my espd-35 and now it powers on with power button and instantly powers off; I can hear it connect and disconnect when plugged into my computer. I see IO35 is connected to the power button as auto off on the schematic. Does this pin need to be set high or low or something on boot?

**Comment by Konstantin-G** [comment]
So if you left that pin LOW in the program, it will turn off immediately, let it be set to HIGH at the beginning of setup()
